In [1]:
import numpy as np
import pandas as pd

In [7]:
s = np.array(5)
print(s,"\n")

v = np.array([1,2,3])
print(v,"\n")

m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m,"\n")

5 

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [8]:
s = np.array(5)
print(s.ndim,"\n")

v = np.array([1,2,3])
print(v.ndim,"\n")

m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m.ndim,"\n")

0 

1 

2 



In [9]:
s = np.array(5)
print(s.shape,"\n")

v = np.array([1,2,3])
print(v.shape,"\n")

m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m.shape,"\n")

() 

(3,) 

(3, 3) 



In [28]:
vec_1 = np.array([[1,2,3,4]])
vec_1 .shape

(1, 4)

In [29]:
w= vec_1.reshape((4,1))
w

array([[1],
       [2],
       [3],
       [4]])

In [31]:
vec_1[:,None]

array([[[1, 2, 3, 4]]])

In [32]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mat.dtype

dtype('int64')

In [33]:
mat = np.array([[0.1,2,3],
                [4,5,6],
                [7,8,9]])
mat.dtype

dtype('float64')

In [34]:
mat = np.array([[0.1,False,3],
                [4,5,6],
                [7,8,9]])
mat.dtype

dtype('float64')

In [ ]:
mat = np.array([[0.1,False,3],
                [4,5,True],
                [7,8,9]])
mat ## => bool dtype not a periority 

array([[0.1, 0. , 3. ],
       [4. , 5. , 1. ],
       [7. , 8. , 9. ]])

In [38]:
class c:
    x=3
o=c()
mat = np.array([[o,False,3],
                [4,5,True],
                [7,8,9]])
print(mat.dtype)
mat

object


array([[<__main__.c object at 0x00000274BFD3D940>, False, 3],
       [4, 5, True],
       [7, 8, 9]], dtype=object)

In [ ]:
'''
so the periority in dtype :
object , string , float , int , bool
'''

In [39]:
m1 = np.ones((3,4))
m2 = np.zeros((5,3))

In [41]:
np.savez('test.npz', ones_mat = m1 , zeros_mat = m2)

In [42]:
with np.load('test.npz')as file:
    mat1 = file['ones_mat']
    mat2 = file['zeros_mat']
    
mat1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])